### ISSUE TITLE
Question: Kubeflow installation's ingress gateway for kfserving is different than an independent install - which gateway to document in kfserving docs? 

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/kfserving#741]
**Clarification Required**

The patch for 1.0.1 Kubeflow manifests now makes the ingress gateway used for prediction for Kubeflow KFServing to be `kfserving-gateway` instead of `istio-ingressgateway`.
kubeflow/manifests#1017

Refer Issues:
#668
#924

Whereas when we install kfserving independently without the help of kubeflow/manifests we still route the requests through `istio-ingressgateway`.

The current documentation refers to the `istio-ingressgateway` as the gateway for prediction requests.

An example is shown here:

https://github.com/kubeflow/kfserving/blob/master/docs/samples/tensorflow/README.md#run-a-prediction

```
CLUSTER_IP=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
```

Whether should we refer to `kfserving-gateway` or `istio-ingressgateway` in the docs?

/cc @yuzisun @animeshsingh @ellis-bigelow @cliveseldon

**Comment by zhenghuiwang** [comment]
+1 to this question. 

Related to this, the basic tensorflow flower example has been broken for a while. (https://github.com/kubeflow/kfserving/issues/734)

**Comment by animeshsingh** [comment]
I think we shall provide both, and users choose based on the situation. 
/assign @animeshsingh

**Comment by jal06** [comment]
It sounds that there is a typo :
the name of the service is kfserving-ingressgateway instead of kfserving-ingressgatway (the letter 'e' is missing in gateway)

Use kfserving-ingressgatway as your INGRESS_GATEWAY if ...
should be 
Use kfserving-ingressgateway as your INGRESS_GATEWAY if ...

**Comment by animeshsingh** [comment]
@jal06 fixed here
https://github.com/kubeflow/kfserving/pull/752

**Comment by jal06** [comment]
@animeshsingh Thanks for fixing the typo.

Getting the CLUSTER_IP works now .
So I agree that this issue must be closed.

However, if I follow the documentation of the flowers-sample example, I still have a problem when getting CLUSTER_IP variable. 
The problem I have now is described in [734](https://github.com/kubeflow/kfserving/issues/734)

I am still not able to run the flowers sample (or any other example).
Please let me know if you need more infos.
